[tools]
"cargo:zootree" = "latest"
codex = "latest"
gh = "latest"
lazygit = "latest"
node = "24"
"npm:@nubjs/nub" = "latest"
"npm:commitizen" = "latest"
"npm:yarn" = "1"
pnpm = "latest"

[settings]
trusted_config_paths = [
  "~/zootree-workspaces"
]
experimental = true
minimum_release_age_excludes = [
  "cargo:zootree"
]

[bootstrap.packages]
"brew:mole" = "latest"
